# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyAssembler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='tags',
            field=models.TextField(default='Tags'),
        ),
    ]
