# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyAssembler', '0002_auto_20170617_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enter_party',
            old_name='usr_nickname',
            new_name='party_has_users',
        ),
        migrations.RenameField(
            model_name='enter_party',
            old_name='party_name',
            new_name='user_has_parties',
        ),
        migrations.AlterField(
            model_name='game',
            name='height_field',
            field=models.IntegerField(default=380),
        ),
        migrations.AlterField(
            model_name='game',
            name='width_field',
            field=models.IntegerField(default=270),
        ),
        migrations.AlterField(
            model_name='party',
            name='related_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_game', to='PartyAssembler.Game'),
        ),
    ]
