# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyAssembler', '0005_auto_20170615_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
