# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 21:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PartyAssembler', '0006_auto_20170615_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter_party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date_time', models.DateTimeField(default=datetime.datetime(2017, 6, 16, 21, 17, 9, 267049, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='create',
            name='party_name',
        ),
        migrations.RemoveField(
            model_name='create',
            name='usr_nickname',
        ),
        migrations.RemoveField(
            model_name='participate',
            name='party_name',
        ),
        migrations.RemoveField(
            model_name='participate',
            name='usr_nickname',
        ),
        migrations.RemoveField(
            model_name='ta_game_user',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='ta_game_user',
            name='user_nickname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='tags',
        ),
        migrations.AddField(
            model_name='party',
            name='leader',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='related_game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Game'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_profile',
            name='idt',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='obs',
            field=models.TextField(default='Observações'),
        ),
        migrations.DeleteModel(
            name='Create',
        ),
        migrations.DeleteModel(
            name='Participate',
        ),
        migrations.DeleteModel(
            name='Ta_Game_User',
        ),
        migrations.AddField(
            model_name='enter_party',
            name='party_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PartyAssembler.Party'),
        ),
        migrations.AddField(
            model_name='enter_party',
            name='usr_nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
