# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PartyAssembler', '0007_auto_20170616_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='obs',
        ),
        migrations.AlterField(
            model_name='enter_party',
            name='entry_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 21, 35, 0, 961323, tzinfo=utc)),
        ),
    ]
