# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 22:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PartyAssembler', '0008_auto_20170616_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter_party',
            name='entry_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 22, 1, 45, 770933, tzinfo=utc)),
        ),
    ]
